//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 CadTools.rc 使用
//
#define IDS_PROJNAME                    100
#define IDC_EDIT1                       101
#define IDS_LBL_ShortCommandName        101
#define IDC_EDIT2                       102
#define IDS_LBL_CommandName             102
#define IDD_GENERICPAIREDITDLG          103
#define IDS_LBL_CommandDescription      103
#define IDC_LABEL1                      104
#define IDS_CommandGroup                104
#define IDC_LABEL2                      105
#define IDS_VAL_LocaleProjectName       105
#define IDC_CHECK1                      106
#define IDS_LBL_PrefixSymbol            106
#define IDC_CHECK2                      107
#define IDS_CMD_yx                      107
#define IDC_BUTTON1                     108
#define IDS_CMD_yxTest                  108
#define IDC_LIST1                       109
#define IDS_CMD_yxSetByLayer            109
#define IDD_MAINBAR                     110
#define IDS_CMD_yxDimensionFix          110
#define IDS_CMD_yxDimensionResume       111
#define IDS_CMD_yxAddSurroundingCharsForDimension 112
#define IDS_CMD_yxRemoveSurroundingCharsForDimension 113
#define IDS_CMD_yxSetBasicBox           114
#define IDS_CMD_yxUnsetBasicBox         115
#define IDS_CMD_yxSetRefDim             116
#define IDS_CMD_yxUnsetRefDim           117
#define IDS_CMD_yxInsertBalloonNumberBlockWithStartNumber 118
#define IDS_CMD_yxPrintClassHierarchy   119
#define IDS_CMD_yxExtractAnnotations    120
#define IDS_CMD_yxUpdateBalloonNumberBlock 121
#define IDS_CMD_yxImeAutoSwitch         122
#define IDS_VAL_Author                  123
#define IDS_VAL_ProjectUrl              124
#define IDS_LBL_SuffixSymbol            125
#define IDS_MSG_CancelOperation         126
#define IDS_LBL_StartNumber             127
#define IDS_LBL_Tip                     128
#define IDS_TIP_yxInsertBalloonNumberBlockWithStartNumber_FMT 129
#define IDS_VAL_LICENSE                 130
#define IDS_ERR_InvalidStartNumber      131
#define IDS_TITLE_SaveCsv               132
#define IDS_ERR_FileOpenFailed          133
#define IDS_MSG_GDT                     134
#define IDS_MSG_MText_FMT               135
#define IDS_MSG_DText_FMT               136
#define IDS_LBL_BalloonNumberHeight     137
#define IDS_MSG_Dimension_FMT           138
#define IDS_MSG_BalloonNextNumber_FMT   139
#define IDS_LBL_AutoStart               140
#define IDS_LBL_Interval                141
#define IDS_ERR_ImeAutoSwitchEmptySetting 142
#define IDS_ERR_InvalidAutoStart        143
#define IDS_ERR_InvalidInterval_FMT     144
#define IDS_ImeAutoSwitchPrompt         145
#define IDS_ImeAutoSwitchStartPrompt_FMT 146
#define IDS_ImeAutoSwitchStopPrompt     147
#define IDS_CMD_yxUnload                148
#define IDS_Msg_Unload_FMT              149
#define IDS_CMD_yxCloneText             150
#define IDS_PROMPT_CopySrcText          151
#define IDS_PROMPT_PasteDstText         152
#define IDS_ERR_NotAngle                153
#define IDS_CMD_yxIntersect             154
#define IDS_CMD_yxBalloonNumberOffset   155
#define IDS_LBL_BalloonNumberOffset     156
#define IDS_MSG_OffsetResultInfo_FMT    157
#define IDS_WARN_OffsetLessZero         158
#define IDS_MSG_OffsetTargetInfo_FMT    159
#define IDS_ERR_BalloonNumberOffsetFail 160
#define IDS_ERR_EmptyBalloonNumberOffset 161
#define IDS_ERR_InvalidInteger          162
#define IDS_TIP_BalloonNumberOffset     163
#define IDS_CMD_yxBalloonNumberFilter   164
#define IDS_TIP_BalloonNumberFilter     165
#define IDS_LBL_BalloonNumberFilterCondition 166
#define IDS_ERR_BalloonNumberFilterEmptyCriteria 167
#define IDS_ERR_BalloonNumberFilterInvalidOperatorType 168
#define IDS_ERR_BalloonNumberFilterNeedInterger 169
#define IDS_Msg_BalloonNumberFilterMatchCount_FMT 170
#define IDS_Msg_NoMatch                 171
#define IDS_Msg_BalloonNumberFilterNoMatch 171
#define IDS_ERR_GetCurrentScaleValue_FMT 172
#define IDS_ERR_LineSpacingFactorOutOfRange 173
#define IDS_FILTER_CsvFiles             174
#define IDS_FILTER_AllFiles             175
#define IDS_FILE_DefaultSaveDataCsv     176
#define IDS_CMD_yxImportCsvToMTextMatrix 177
#define IDS_TITLE_ImportCsv             178
#define IDS_LBL_Parameter               179
#define IDS_TIP_MTextMatrixParameter    180
#define IDS_ERR_EmptyMTextMatrixParameter 181
#define IDS_PROMPT_GetPoint             182
#define IDS_CMD_yxSpatialTableExplorer  183
#define IDS_TIP_SpatialTableExplorerParameter 184
#define IDS_MSG_FileLocation_FMT        185
#define IDS_MSG_MTextPos_FMT            186
#define IDS_MSG_DTextPos_FMT            187
#define IDS_CMD_yxCheckBalloonNumberMaxMin 188
#define IDS_MSG_PrintBalloonNumberMaxAndMin_FMT 189
#define IDS_MSG_EmptyBalloonNumber      190
#define IDS_CMD_yxPasteClipImage        191
#define IDS_WARN_PasteClipNoImage       192
#define IDS_TITLE_SaveImage             193
#define IDS_FILTER_PngFiles             194
#define IDS_FILE_Png                    195
#define IDS_ERR_CopyFileToClipboardFail 196
#define IDS_ERR_SaveClipboardBitmapToFileFail 197
#define IDS_CMD_yxLocateDrawing         198
#define IDS_ERR_DrawingNoSave           199
#define IDS_ERR_LocateFailed            200
#define IDS_ERR_FileNotFound            201
#define IDS_ERR_AccessDenied            202
#define IDS_ERR_Unknown_FMT             203

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        126
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         110
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
